spring:
  application:
    name: rabbitmq-boot
  rabbitmq:
    host: 121.5.224.141
    username: admin
    password: admin
    virtual-host: /
    port: 5672
    publisher-returns: true
    publisher-confirm-type: correlated
    listener:
      simple:
        acknowledge-mode: manual

server:
  port: 8088

